### ISSUE TITLE
bump ocis commit id

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#1081]
don't wait for the new pact-js version, lets sort out the ocis commit id now

hopefully we can get much more tests out of the pending state

**Comment by saw-jan** [comment]
Tasks:
- [ ] bump oCIS commit id (https://github.com/owncloud/owncloud-sdk/pull/1085)
- [ ] check if any tests are out of pending state

**Comment by saw-jan** [comment]
Closing this in favour of https://github.com/owncloud/owncloud-sdk/issues/1089
