### ISSUE TITLE
Can't Login Owncloud

### ISSUE THREAD

**Issue by ajakapong** [owncloud/owncloud-sdk#238]
TypeError: Cannot read property 'data' of undefined
    at owncloud.js:8
    at owncloud.js:1
    at owncloud.js:1
    at MutationObserver.a (owncloud.js:8

**Comment by DeepDiver1975** [comment]
mind sharing the code you are using? THX

**Comment by DeepDiver1975** [comment]
I'll reopen this issue once there is feedback
