### ISSUE TITLE
Publish as github package

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/owncloud-sdk#258]
Github Package Registry ( https://help.github.com/en/articles/about-github-package-registry ) is available.

It would be great to publish the sdk on github directly to become independent from NPM 

Steps for publishing
https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry#publishing-a-package

**Comment by DeepDiver1975** [comment]
I gave this a try and it looks like this feature is still in beta and you need to sign up to get this enabled.

I suggest to postpone this for the time being .... let's reopen this once this feature is out of beta.

THX
