### ISSUE TITLE
Question: Can I use this write NodeJS logs to owncloud 

### ISSUE THREAD

**Issue by jeffreybarron** [owncloud/owncloud-sdk#288]
Hi Folks,

Im looking for a solution that allows me to write logs and json documents to a file system that can be viewed and downloaded by my user.

Your readme say "Supports only browser JS but requires Javascript" though, and I want to do this in nodejs on the backend?

Sorry if this is not the place, I'm kind of new to this.

Many Thanks for your great work and help

**Comment by jeffreybarron** [comment]
if what I'm looking for is possible, Id really deeply appreciate if you could provide me a little code snippet example of how to 

here are some of the operations I use,
Note Im using Bunyan to write to the local host, and would like this to go to owncloud
and Im using filesystem to write application documents
see jeffreybarron/UOW-OnlineSTM


const fs = require("fs");
const bunyan = require("bunyan");
const log = bunyan.createLogger({
  name: "UOW_CogLab",
  streams: [{
      level: "debug",
      path: __dirname + "/logs/ostm-log.json"
    },
    {
      level: "info",
      stream: process.stdout
    }
  ],
  src: true
});

function fileExists(sURL) {
  return new Promise((resolve, reject) => {
    let fileExists = fs.existsSync(sURL);
    if (fileExists) {
      resolve(fileExists);
    } else {
      reject("File does not exist.");
    }
  });
}

function readFile(sURL) {
  return new Promise((resolve, reject) => {
    fs.readFile(sURL, "utf8", (err, data) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(data);
    });
  });
}

function writeJSON(sURL, data) {
  return new Promise((resolve, reject) => {
    var sFile = JSON.stringify(data, null, 2);
    fs.writeFile(sURL, sFile, "utf-8", function (err) {
      if (err) {
        //Deal with error
        return reject(err);
      } else {
        return resolve(data);
      }
    });
  });
}

**Comment by DeepDiver1975** [comment]
At the moment we only support browsers as stated in the README.

We will add support for NodeJS in the future - but there are no explicit plans at the moment. Sorry
