### ISSUE TITLE
Slow compilation / watcher

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud-sdk#376]
If first compile takes a while, ok.

But when running a watcher using karma (not single shot mode), it should only recompile the modified files like we do in Phoenix.

In Phoenix it compiles much faster after a single file change. Maybe we need to tweak the webpack config for that.

**Comment by DeepDiver1975** [comment]
We can actually get rid of webpack for the released package - I originally introduced this to get transpiling in place. This can now be done in phoenix as well.

Benefit would be that in debug builds the sdk can be debugged properly.

This could also help in making test execution smoother .... maybe ..... hopefully .... :man_shrugging:

**Comment by PVince81** [comment]
we might still need to transpile ES6 when running tests

**Comment by pascalwengerter** [comment]
Closing as outdated, building the system takes 2.7 seconds and running it with `--watch` appended results in rebuilds in the ~2s range
