### ISSUE TITLE
Test order shouldn't be important

### ISSUE THREAD

**Issue by noveens** [owncloud/owncloud-sdk#39]
Clean up after each test.

**Comment by PVince81** [comment]
I also think all of "test.js" should be split further into separate files, one for each module "files", "sharing", etc. The unauthenticated/unauthorized stuff can stay in single files.

**Comment by PVince81** [comment]
blocks https://github.com/owncloud/js-owncloud-client/pull/86

**Comment by PVince81** [comment]
bonus: use async/await in the test, would make it more readable than promises ?

**Comment by dpakach** [comment]
After #645 and #646 this is no logner an issue
