### ISSUE TITLE
create tests for functions that were only tested in before/after steps

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#558]
when converting the test to pact.io we do delete unneeded beforAll/afterAll functions e.g https://github.com/owncloud/owncloud-sdk/pull/555/files#diff-61b7a289e66f2a03d80121c9dbdd8f0dL26
after finishing the conversion work, we need to check which parts of the sdk was only covered by those steps and not explicit tests and write more tests for those

CC @LukasHirt

**Comment by HariBhandari07** [comment]
Except for `groupTest.js` all other files have general tests like `user creation`, `file creation`, `file deletion` etc. in the before and after steps. As these general tests are already covered in their respective files, this issue is closed.
