### ISSUE TITLE
dedublicate oc object creation in tests 

### ISSUE THREAD

**Issue by swoichha** [owncloud/owncloud-sdk#581]
In `tests/appsTest.js` we have   https://github.com/owncloud/owncloud-sdk/blob/3cf331b26bff8aa64e320d4975cafe2c6cf866a4/tests/appsTest.js#L15-L24 

Similar code can be found in `tests/loginTest.js`
https://github.com/owncloud/owncloud-sdk/blob/3cf331b26bff8aa64e320d4975cafe2c6cf866a4/tests/loginTest.js#L80-L88

We need to refactor it. Maybe we can make a function for it. Also, need to check if there are other code repetition. 

TODO:
1. use `createOwncloud` function from `pactHelper` to create standard oc instance for tests wherever it applies.
2. use `pactCleanup` function from `pactHelper` to verify the provider and clear the interactions for tests wherever it applies.

**Comment by dpakach** [comment]
###  Tests to be verified
- [ ] -unauthenticated 
    - [ ] - appTest.js
    - [ ] - capabilitiesTest.js
    - [ ] - filesTest.js
    - [ ] - groupTest.js
    - [ ] - sharingTest.js
    - [ ] - userTest.js

- [ ] -unauthorized  
    - [ ] - appTest.js 
    - [ ] - capabilitiesTest.js  
    - [ ] - filesTest.js  
    - [ ] - groupTest.js 
    - [ ] - sharingTest.js 
    - [ ] - userTest.js 

- [ ] - appTest.js  
- [ ] - capabilitiesTest.js 
- [ ] - filesTest.js 
- [ ] - filesTrashTest.js 
- [ ] - fileVersionTest.js 
- [ ] - groupTest.js 
- [ ] - loginTest.js (not needed)
- [ ] - publickLinkTest.js wip 
- [ ] - requestsOcsTest.js 
- [ ] - shareRecipientTest.js 
- [ ] - sharingTest.js @jasson99 
- [ ] - sharingWithAttributesTest.js 
- [ ] - signedUrlTest.js
- [ ] - signedUrlIntegrationTest.js 
- [ ] - userTest.js 
- [ ] - xmlParserTest.js
- [ ] - signUrlTest.js

**Comment by dpakach** [comment]
done
