### ISSUE TITLE
client.login() should return user object instead of "true"

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/owncloud-sdk#59]
I propose to return the user object after successfully logging in, instead of a superfluous `true`.

```
owncloud.client.login("username", "s3cr37").then((status) => {
	// status = true, but we don't need to know that here
});
```

**Comment by PVince81** [comment]
sounds good

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/owncloud-sdk/blob/7ce1368a1c199e3cf9537a38d1b64e9f20a36682/src/owncloud.js#L85

implemented
