### ISSUE TITLE
client.login() with invalid credentials returns unexpected error

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/owncloud-sdk#60]
If you try logging in using invalid credentials, the method throws _'Please provide a valid owncloud instance'_, even tho valid credentials do work.

Thus we can conclude, the error message is wrong since the instance is valid.
```
OC.client.login("username", "this password is wrong").catch(error => {
	// error <- not what is to be expected
});
```

**Comment by DeepDiver1975** [comment]
this should no longer be the case
