### ISSUE TITLE
adjust pact interactions so that they also pass provider side (oc10)

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#709]
follow up of #662
sub task of #644

Currently we run all tests of the consumer pact against the oc10 provider but most of them fail, see #662 because the contract from the consumer side is not correct or missing given steps.
All failing interactions need to be adjusted, so that the provider accepts them.

**Comment by saw-jan** [comment]
Tests to be adjusted

 - [ ] unauthenticated
   - [ ] appTest.js
   - [ ] capabilitiesTest.js
   - [ ] filesTest.js
   - [ ] groupTest.js
   - [ ] sharingTest.js
   - [ ] userTest.js
 
- [ ] unauthorized
  - [ ] appTest.js
  - [ ] capabilitiesTest.js
  - [ ] filesTest.js
  - [ ] groupTest.js
  - [ ] sharingTest.js
  - [ ] userTest.js
  - [ ] appTest.js

 - [ ] capabilitiesTest.js

 - [ ] filesTest.js wip @dpakach

 - [ ] filesTrashTest.js

 - [ ] fileVersionTest.js

 - [ ] groupTest.js

 - [ ] loginTest.js

 - [ ] publickLinkTest.js

 - [ ] requestsOcsTest.js

 - [ ] shareRecipientTest.js

 - [ ] sharingTest.js

 - [ ] sharingWithAttributesTest.js wip

 - [ ] signedUrlIntegrationTest.js

 - [ ] signUrlTest.js

 - [ ] userTest.js

 - [ ] xmlParserTest.js
