### ISSUE TITLE
replace davclient.js with perry-mitchell/webdav-client

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#712]
subtask of #705

the current davclient is not working on node, so we need to replace it with a client that works with node as well as browsers.
one possibility is https://github.com/perry-mitchell/webdav-client
It used not to support customer dav props see https://github.com/perry-mitchell/webdav-client/pull/165 (current status need to be researched and if needed an upstream PR need to be created)

**Comment by dpakach** [comment]
Fixed by #735
