### ISSUE TITLE
adjust pact interactions so that they also pass provider side (ocis)

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#747]
follow up of #740
sub task of #644

Currently we run all tests of the consumer pact against the ocis provider but most of them fail, see #740 because the contract from the consumer side is not correct or missing given steps.
All failing interactions need to be adjusted, so that the provider accepts them.

**Comment by saw-jan** [comment]
Tests to check

- [ ] unauthorized
  - [ ] appTest.js
  - [ ] capabilitiesTest.js
  - [ ] filesTest.js
  - [ ] groupTest.js
  - [ ] sharingTest.js
  - [ ] userTest.js

- [ ] appTest.js
 
 - [ ] capabilitiesTest.js

 - [ ] filesTest.js

 - [ ] filesTrashTest.js

 - [ ] fileVersionTest.js

 - [ ] groupTest.js

 - [ ] loginTest.js

 - [ ] pactHelper.js

 - [ ] publickLinkTest.js

 - [ ] requestsOcsTest.js
 
 - [ ] shareRecipientTest.js

 - [ ] sharingTest.js

 - [ ] sharingWithAttributesTest.js

 - [ ] signedUrlIntegrationTest.js

 - [ ] userTest.js
