### ISSUE TITLE
[Tests-Only] Fix pact interactions for provider side tests

### ISSUE THREAD

**Issue by dpakach** [owncloud/owncloud-sdk#780]
Part of https://github.com/owncloud/owncloud-sdk/issues/644
#### For oc10 backend
- [x] - tests/FilesTrashTest.js https://github.com/owncloud/owncloud-sdk/pull/798 
- [x] - tests/FilesVersionTest.js https://github.com/owncloud/owncloud-sdk/pull/798 
- [x] - tests/PublicLinkTest.js https://github.com/owncloud/owncloud-sdk/pull/791
- [x] - tests/FilesTest.js  https://github.com/owncloud/owncloud-sdk/pull/797
- [x] - tests/unauthorized/FilesTest.js https://github.com/owncloud/owncloud-sdk/pull/782

#### For ocis backend
- [x] - tests/FilesTrashTest.js https://github.com/owncloud/owncloud-sdk/pull/798 
- [x] - tests/FilesVersionTest.js https://github.com/owncloud/owncloud-sdk/pull/798 
- [x] - tests/PublicLinkTest.js https://github.com/owncloud/owncloud-sdk/pull/815
- [x] - tests/FilesTest.js https://github.com/owncloud/owncloud-sdk/pull/811
- [x] - tests/unauthorized/FilesTest.js https://github.com/owncloud/owncloud-sdk/pull/815

**Comment by saw-jan** [comment]
All above-listed tests' interactions have been adjusted for servers
