### ISSUE TITLE
filter by tag test should not rely on uploading file, creating tag and tagging file

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#789]
- [x]  make sure `it('checking method: filter by tag'` only test `getFilesByTags` and does not rely on `fileInfo` `getFileId` `createTag` `tagFile` and the respected interactions https://github.com/owncloud/owncloud-sdk/pull/792
- [x] make sure  `fileInfo` `getFileId` `createTag` `tagFile` are tested in separate tests (find those tests or create new if none exist) https://github.com/owncloud/owncloud-sdk/pull/792

**Comment by kiranparajuli589** [comment]
done with https://github.com/owncloud/owncloud-sdk/pull/792
