### ISSUE TITLE
Prevent running of failing nightly tests

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/owncloud-sdk#870]
When I visit https://drone.owncloud.com/owncloud/owncloud-sdk I see a `nightly` run that fails (almost) every night. 

Is there a good explanation for this? Otherwise I'd suggest we should be more sophisticated with our tools and only run CI if it's necessary

**Comment by phil-davis** [comment]
There is no code in `.drone.star` to report a result to the builds channel of the chat, or anywhere. So nobody monitors this.

If you think that there are PRs happening often enough that we don't need a nightly double-check of CI/tests, then remove the nightly job from drone.

But maybe we should look at why CI  fails in nightly directly on master branch, but it passes in PRs (for example #869 passed a few hours ago)

**Comment by pascalwengerter** [comment]
Since we've made the switch to SemVer and don't publish new versions upon successful CI runs anymore I've removed the `nightly` cron job from Drone and will close this issue. Thanks for the input @phil-davis
