### ISSUE TITLE
update pact-js library

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#924]
our version of the pact-js library is pretty old, so it need to be updated. There are some breaking changes in the current version

**Comment by individual-it** [comment]
currently this is blocked by a dependency of the pact-js library
waiting for https://github.com/node-ffi-napi/ref-napi/pull/64
see also https://github.com/pact-foundation/pact-js/pull/759

**Comment by individual-it** [comment]
the V3 branch of pact-js is broken currently and blocked itself by a dependency issue. We don't have the knowledge to fix the dependencies, so we are stuck here.

**Comment by phil-davis** [comment]
@individual-it any update on pact-js V3?

**Comment by individual-it** [comment]
trying it in #1019 
on consumer side tests down to
![grafik](https://user-images.githubusercontent.com/2425577/156713744-fa527865-7256-453c-8eb2-86d01cc186d0.png)

**Comment by pascalwengerter** [comment]
> blocked for now because of #924

@kiranparajuli589 you mention the issue in itself, what did you want to reference here?;)

**Comment by kiranparajuli589** [comment]
> blocked for now because of ~~#924~~ https://github.com/owncloud/owncloud-sdk/pull/1019#issuecomment-1072281632

sorry :) I meant this comment.

**Comment by phil-davis** [comment]
The latest reason for being blocked seems to be https://github.com/pact-foundation/pact-js/issues/848

**Comment by individual-it** [comment]
I think we will also be blocked by https://github.com/pact-foundation/pact-js/issues/884

**Comment by individual-it** [comment]
@kulmann there would be an ugly workaround for https://github.com/pact-foundation/pact-js/issues/848 but nothing I can find to do about an other issue https://github.com/pact-foundation/pact-js/issues/884 :-(

**Comment by phil-davis** [comment]
Note: the tests still need to use node 14:
```
nvm install 14
```

A lot of developers/testers have node 16 these days. So that is a little trick that people need to realize until this issue gets fixed, and we can use later pact stuff.

**Comment by nabim777** [comment]
https://github.com/owncloud/owncloud-sdk/pull/1019#issuecomment-1948269552
