### ISSUE TITLE
Reason to add xmldom to Dependecy

### ISSUE THREAD

**Issue by jeremia49** [owncloud/owncloud-sdk#938]
Are there any reason to add xmldom to dependecy ? 
I tried to remove the xmldom and ran the consumer tests locally, and it turns out it PASS the tests.

If there are some reason to use xmldom, you should replace it to  https://github.com/xmldom/xmldom because jindw/xmldom#259

GH-908

**Comment by pascalwengerter** [comment]
Closed via #939 thanks to @jeremia49
