### ISSUE TITLE
Drop support for webdav v1

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-sdk#958]
We're currently planning to drop support for webdav (v1) in favour of the new dav implementation (v2), which is fully supported by both ownCloud 10 and ownCloud Infinite Scale.

Would like to hear if there are objections to this.

**Comment by kulmann** [comment]
cc @rpocklin

**Comment by kulmann** [comment]
cc @phil-davis @individual-it

**Comment by phil-davis** [comment]
I don't see a problem with that. All server implementations have the "new" webdav v2. So clients and client infrastructure does not have to know anything about "old" webdav v1.

**Comment by fschade** [comment]
Is there a reason why ownCloud classic to still supports webdav (v1)? If i get it right dav (v2) has the same set of features!?

So if we do not miss something i vote to drop it.

**Comment by DeepDiver1975** [comment]
v1 only serves the files of the currently logged in user
v1 serves files, calendar, contacts, trashbin and many more following the URI principle that URIs are truly unique ...

remote.php/webdav/welcome.txt is not unique as it depends on the logged in user
remote.php/dav/files/alice/welcome.txt in contrary is unique 

the over all plan was once to even allow cross-user operations like copying files from one user space to another .... but we never got there ...

**Comment by DeepDiver1975** [comment]
> So if we do not miss something i vote to drop it.

from the sdk perspective there is no reason to stay with v1 - it should have been used right from the beginning :see_no_evil:

**Comment by JanAckermann** [comment]
@DeepDiver1975 Thx, so we will proceed with replace v1 with v2

**Comment by JanAckermann** [comment]
@butonic But if we release a new major version, this might ain’t an issue ?

**Comment by pascalwengerter** [comment]
> @butonic But if we release a new major version, this might ain’t an issue ?

We should switch the whole thing over to the way we do semver in the other web-related repos I suggest :)

**Comment by kulmann** [comment]
> Um, might be needed for cernbox @kulmann

@diocas @elizavetaRa do you maybe know?

**Comment by diocas** [comment]
For CERNBox should not matter, assuming that OCIS has the correct implementation.
